# Required build root directory. This should match
# the folder that composer.json is using in installer
# paths.
build:
  root: www

# Required temporary directory for build tasks.
temp: /tmp

# Symbolic links to create for the project
# Do not include the build root defined
# above in the destination.
symlinks:
  settings:
    source: local/settings.php
    destination: sites/default/settings.php
  settings.local:
    source: local/settings.local.php
    destination: sites/default/settings.local.php
  files:
    source: local/files
    destination: sites/default/files

# Environments for deployments.
environments:
  production:
    git:
      uri: git@gitlab.com:[namespace]/[project].git
      branch: master
      # Optional sub-directory to use in the artifact repo for builds.
      # The default is to build into the root of the project.
      sub_dir: docroot
    # Tasks to be executed when running "boici build:tasks production"
    tasks:
      npm:
        directory: sites/all/themes/custom/custom_theme
        command: npm install
